# Generated by Django 3.2 on 2021-04-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210423_0309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artista',
            new_name='Artist',
        ),
    ]
