# Generated by Django 3.2 on 2021-05-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_album_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='timesplayed',
            new_name='times_played',
        ),
    ]
